### PR TITLE
add transient for org mode

### PR DESCRIPTION
**Pull request by dogayuksel**
Hey James,

I am still working on it, I have some things to figure out, pushing it so that you are aware.

-- Keeping transients open for only certain commands doesn't seem to be possible yet.
-- Will look into adding dynamic titles. (`Org: %s(matcha-heading-current-file)` in this case)

-- Adds 'org-reveal' command that are different then the original hydras.
-- Adds timer-stop to replace duplicated pause-or-continue command

Best,
Doga

### CODE REVIEW

**Comment by jojojames** [comment]
Nice, I've started moving my hydras to transients (as well as moving some hydras that I don't use anymore.)

> Keeping transients open for only certain commands doesn't seem to be possible yet.

Supposedly, it's possible but I haven't tried it.

https://magit.vc/manual/transient/Comparison-With-Other-Packages.html#Comparison-With-Other-Packages

> Will look into adding dynamic titles. (Org: %s(matcha-heading-current-file) in this case)

Yeah I wanted these too in my other transients. I was too lazy to look it up to see if it's possible though.

Let me know when you think it's good to merge. Looks good.

**Comment by jojojames** [comment]
Also I think it'd be cool to have names of commands that leads to other transients to be suffixed with "...".

e.g.

```
(define-transient-command matcha-tide-mode
  "Typescript"
  [["Actions"
    ("e" "Eval..." matcha-tide-eval)
```

**Comment by dogayuksel** [comment]
Should be good to merge now.

- To persist the transient for a single suffix:
`("e" "Element" org-mark-element :transient t)`

- To have a dynamic string you can pass a function to description:
`:description (lambda () (format "Org: %s" (matcha-heading-current-file)))`

Transients behave a slightly different then hydras, I guess they will need some tweaks after some use.

**Comment by jojojames** [comment]
Nice, awesome, thanks!

**Pull request merged**
